#include <iostream>
#include <cmath>
using namespace std;
int main()
{
    int x;
    double i,p ;
   if(x=pogative)
   {
    cout<< "please input usage :"<<endl;
    cin>>x;
   else
    cout<<"Invalid Input !!!"<<endl;
    cin>>x; 
   }
    cout<<"please input voltage :"<<endl;
    cin>>x;}
    
    if(i<=150)
    cout<<"electricity cost:"<<endl;
    cin>> i;
    
    if(i<=400&&i>=151)
    cout<<"electricity cost:"<<end;
    cin>> i;
    
    else(i>401)
    cout<<"electricity cost:"<<endl;
    cin i;
    

    p(p>=22||<=33) = 2.4649*electricity cots
    p(p<22) = 1.8047*electricity cots
    vat 7% = (electricity cots*x)*7/100
    Total cost = (electricity cots*x)+service+(ft*electricity)+vat 7%
    
    
    system ("pause");
    return 0;
}
